#1404 Corrected Repeated contact-us
SauravMukherjee44/Aec-Library-Website pull request #1409
Opened 2023-07-02 11:45 UTC by PVBharadwaj

### 🛠️ Fixes Issue

#1404 

### 👨‍💻 Changes proposed

In the resources section contact us appeared two times. It is fixed.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

### 📷 Screenshots
The webpage was previously like the screenshot shown below 
<img width="956" alt="Screenshot 2023-07-01 160045" src="https://github.com/SauravMukherjee44/Aec-Library-Website/assets/117581755/ae6b9e90-76cb-4b69-8aa8-8415afe31c53">

It was changed to this.
<img width="959" alt="image" src="https://github.com/SauravMukherjee44/Aec-Library-Website/assets/117581755/a1d6d113-7663-4d2a-ad80-ba727c1ab3f6">

2023-07-02 11:46 UTC, PVBharadwaj commented
@rohanbabbar04  please review this pr under GSSoC'23

2023-07-02 14:55 UTC, rohanbabbar04 requested changes
![image](https://github.com/SauravMukherjee44/Aec-Library-Website/assets/77425744/318b1af0-f535-45c0-b0eb-3fea4163e7ab)
Make sure it works for all screen sizes....

2023-07-02 14:55 UTC, rohanbabbar04 commented on resource.html
> +                    </a></div> -->
Remove this line, don't comment code...

2023-07-03 06:57 UTC, PVBharadwaj commented
@rohanbabbar04  I have made the required changes and created a new pr ( #1411 ) for the same issues. Please close this pr and review that pr

2023-07-11 05:55 UTC, closed without merging