I add more resource in home page
SauravMukherjee44/Aec-Library-Website pull request #759
Opened 2022-03-09 15:41 UTC by Payalsahb20220

Hello @devaaquib sir  , I added more resources in Home page. Please accept my pull request:)
Here is screenshot after adding more resource.
![Screenshot (57)](https://user-images.githubusercontent.com/83233449/157475944-56944bc7-0b49-49c5-a5d7-3fc7f5e3ca14.png)

2022-03-09 16:45 UTC, devaaquib requested changes
@Payalsahb20220  Please resolved the conflict?

2022-03-11 10:05 UTC, devaaquib approved these changes

2022-03-14 10:12 UTC, devaaquib approved these changes

2022-03-14 10:15 UTC, devaaquib commented
@Payalsahb20220 Can you please mention your issue number here.

2022-03-24 12:30 UTC, Anshika-Srivastava requested changes
Hey @Payalsahb20220 adding more blogs have increased the page length. Please add a slider for the same.

2023-07-31 18:20 UTC, closed without merging