Customized General message section of resource page(issue #682)
SauravMukherjee44/Aec-Library-Website pull request #768
Opened 2022-03-10 14:30 UTC by DeveloperAshish8

Changed the message displaying as a link to paragraph in the general message section of resource page.

### 🛠️ Fixes Issue

### 👨‍💻 Changes proposed

### ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

### 📷 Screenshots
![Screenshot (1)](https://user-images.githubusercontent.com/90233808/157681740-075f5049-c07a-43ce-b38d-b38b64dbb694.png)
![Screenshot (2)](https://user-images.githubusercontent.com/90233808/157681796-4160946d-6b71-4b24-ab4c-77074f3cde25.png)

2022-03-11 09:56 UTC, devaaquib approved these changes

2022-03-11 09:56 UTC, devaaquib requested changes
@DeveloperAshish8 Please resolved the conflict!

2022-03-14 10:09 UTC, devaaquib reviewed
@DeveloperAshish8 Please remove the extra line spacing.

2022-03-19 05:31 UTC, SauravMukherjee44 approved these changes

2022-03-19 05:32 UTC, merged