Added Icons Instead Of Play button In Listen To Audio Books Section
SauravMukherjee44/Aec-Library-Website pull request #997
Opened 2022-10-07 08:59 UTC by RishitaGangwal

#923  🛠️ Fixes Issue

### 👨‍💻 Changes proposed

### ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

### 📷 Screenshots

2022-10-08 17:04 UTC, IAmTamal requested changes
Reduce the size of pause and play button
It looks extremely large. Make it half of it's size

2022-10-09 15:47 UTC, IAmTamal approved these changes
LGTM ✅

2022-10-09 16:45 UTC, RishitaGangwal commented
Thankyou ❤

2022-10-09 20:08 UTC, SauravMukherjee44 approved these changes

2022-10-09 20:08 UTC, merged